import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Card,
  Input,
  Button,
  message,
  Spin,
  Tabs,
  Select,
  Row,
  Col,
  Typography,
} from 'antd';
import {
  PictureOutlined,
  DownloadOutlined,
  SendOutlined,
} from '@ant-design/icons';
import ImageArrayUpload from '../../components/ImageArrayUpload';
import { useTempImages } from '../../hooks/useTempImages';
import { useSearchParams } from 'react-router-dom';
import { text2img, img2img } from '../../api/image';
import type { GenerationResponse, Text2ImgRequest, Img2ImgRequest } from '../../api/image';
import { useThrottle } from '../../hooks/useDebounce';
import './index.css';

const { TextArea } = Input;
const { Title, Paragraph } = Typography;

const styleOptions = [
  { value: 'realistic', label: '写实风格' },
  { value: 'anime', label: '动漫风格' },
  { value: 'cyberpunk', label: '赛博朋克' },
  { value: 'watercolor', label: '水彩风格' },
  { value: 'oil_painting', label: '油画风格' },
  { value: 'sketch', label: '素描风格' },
  { value: 'chinese', label: '国潮风格' },
  { value: '3d', label: '3D渲染' },
];

const loadingHints = [
  '正在铺设整体构图与光影…',
  '角色细节与氛围正在逐步成型…',
  '马上进入高清出图阶段…',
];

const Generate: React.FC = () => {
  const [searchParams] = useSearchParams();
  const initialPrompt = searchParams.get('prompt') || '';

  const [prompt, setPrompt] = useState(initialPrompt);
  const [style, setStyle] = useState('realistic');
  const [loading, setLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [imageLoaded, setImageLoaded] = useState(false);
  const [loadingHintIndex, setLoadingHintIndex] = useState(0);
  const [imageUrls, setImageUrls] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState('text2img');
  const { addTempUrl, removeTempUrl, cleanup } = useTempImages();
  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    if (!loading) {
      setLoadingHintIndex(0);
      return;
    }

    const timer = window.setInterval(() => {
      setLoadingHintIndex((prev) => (prev + 1) % loadingHints.length);
    }, 1800);

    return () => window.clearInterval(timer);
  }, [loading]);

  const applyGenerationResponse = useCallback((res: GenerationResponse) => {
    if (res.taskStatus === 'RUNNING') {
      message.info(res.message || '图片正在生成中，请稍候...');
      return;
    }

    if (res.taskStatus === 'SUCCESS' && res.result) {
      const nextImage = res.result.ossUrl || res.result.imageUrl || '';
      if (!nextImage) {
        message.error('未获取到生成图片，请稍后重试');
        return;
      }

      setImageLoaded(false);
      setGeneratedImage(nextImage);
      message.success('图片生成成功！');
      return;
    }

    if (res.taskStatus === 'FAILED') {
      message.error(res.message || '生成失败');
    }
  }, []);

  // 文生图
  const handleTextToImage = useCallback(async () => {
    if (!prompt.trim()) {
      message.warning('请输入提示词描述');
      return;
    }

    setLoading(true);
    try {
      const requestParams: Text2ImgRequest = {
        prompt: prompt.trim(),
        style: style,
        aspectRatio: '1:1',
        imageSize: '1K',
      };

      const response = await text2img(requestParams) as unknown as { code: number; data: GenerationResponse; message?: string };
      if (response.code === 200 && response.data) {
        applyGenerationResponse(response.data);
      } else {
        message.error(response.message || '生成失败');
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { message?: string } } };
      message.error(err.response?.data?.message || '生成失败，请稍后重试');
    } finally {
      setLoading(false);
    }
  }, [applyGenerationResponse, prompt, style]);

  // 使用节流，防止用户频繁点击（2秒内只能点击一次）
  const throttledTextToImage = useThrottle(handleTextToImage, 2000);

  // 如果有初始prompt，自动开始生成
  useEffect(() => {
    if (!initialPrompt || autoGeneratedRef.current) {
      return;
    }

    autoGeneratedRef.current = true;
    throttledTextToImage();
  }, [initialPrompt, throttledTextToImage]);

  // 图生图
  const handleImageToImage = useCallback(async () => {
    if (!prompt.trim()) {
      message.warning('请输入提示词描述');
      return;
    }
    if (imageUrls.length === 0) {
      message.warning('请上传参考图片');
      return;
    }

    setLoading(true);
    try {
      const requestParams: Img2ImgRequest = {
        prompt: prompt.trim(),
        style: style,
        aspectRatio: '1:1',
        imageSize: '1K',
        imageUrls,
      };

      const response = await img2img(requestParams) as unknown as { code: number; data: GenerationResponse; message?: string };
      if (response.code === 200 && response.data) {
        applyGenerationResponse(response.data);
      } else {
        message.error(response.message || '生成失败');
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { message?: string } } };
      message.error(err.response?.data?.message || '生成失败，请稍后重试');
    } finally {
      setLoading(false);
      await cleanup();
    }
  }, [applyGenerationResponse, prompt, style, imageUrls, cleanup]);

  // 使用节流，防止用户频繁点击（2秒内只能点击一次）
  const throttledImageToImage = useThrottle(handleImageToImage, 2000);

  // 下载图片
  const handleDownload = () => {
    if (!generatedImage) return;
    const link = document.createElement('a');
    link.href = generatedImage;
    link.download = `pixel-ai-${Date.now()}.png`;
    link.click();
  };

  const tabItems = [
    {
      key: 'text2img',
      label: '文生图',
      children: (
        <div className="generate-form">
          <div className="form-item">
            <label>提示词描述</label>
            <TextArea
              placeholder="描述你想要生成的头像，例如：一个戴着墨镜的酷炫年轻人，赛博朋克风格，霓虹灯背景"
              rows={4}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              maxLength={500}
              showCount
            />
          </div>
          <div className="form-item">
            <label>风格选择</label>
            <Select
              value={style}
              onChange={setStyle}
              options={styleOptions}
              style={{ width: '100%' }}
            />
          </div>
          <Button
            type="primary"
            icon={<SendOutlined />}
            size="large"
            onClick={throttledTextToImage}
            loading={loading}
            block
          >
            生成头像
          </Button>
        </div>
      ),
    },
    {
      key: 'img2img',
      label: `图生图${imageUrls.length > 0 ? ` (${imageUrls.length})` : ''}`,
      children: (
        <div className="generate-form">
          <div className="form-item">
            <label>上传参考图片</label>
            <ImageArrayUpload
              value={imageUrls}
              onChange={setImageUrls}
              onTempUrlAdd={addTempUrl}
              onTempUrlRemove={removeTempUrl}
              maxCount={10}
            />
          </div>
          <div className="form-item">
            <label>描述你想要的效果</label>
            <TextArea
              placeholder="描述你想要的变化效果，例如：将这张照片转换成动漫风格，保留人物特征"
              rows={4}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              maxLength={500}
              showCount
            />
          </div>
          <div className="form-item">
            <label>风格选择</label>
            <Select
              value={style}
              onChange={setStyle}
              options={styleOptions}
              style={{ width: '100%' }}
            />
          </div>
          <Button
            type="primary"
            icon={<SendOutlined />}
            size="large"
            onClick={throttledImageToImage}
            loading={loading}
            block
          >
            生成头像
          </Button>
        </div>
      ),
    },
  ];

  const showResultOverlay = loading || (!!generatedImage && !imageLoaded);
  const resultOverlayTitle = loading
    ? loadingHints[loadingHintIndex]
    : '图片正在加载，马上完整呈现';
  const resultOverlayDescription = loading
    ? generatedImage
      ? '已为你保留上一张结果，新图会从上到下自然展开。'
      : '从整体轮廓到细节高光，画面会逐步完善。'
    : '高清预览已返回，正在为你做更丝滑的进场动画。';

  return (
    <div className="generate-container">
      <div className="page-header">
        <Title level={2}>
          <PictureOutlined /> AI头像生成
        </Title>
        <Paragraph type="secondary">
          输入描述或上传照片，AI帮你生成专属头像
        </Paragraph>
      </div>

      <Row gutter={24}>
        <Col xs={24} lg={12}>
          <Card title="生成设置" className="input-card">
            <Tabs
              activeKey={activeTab}
              onChange={setActiveTab}
              items={tabItems}
            />
          </Card>
        </Col>

        <Col xs={24} lg={12}>
          <Card
            title="生成结果"
            className="result-card"
            extra={
              generatedImage && (
                <Button
                  type="primary"
                  icon={<DownloadOutlined />}
                  onClick={handleDownload}
                >
                  下载
                </Button>
              )
            }
          >
            <div className="result-content">
              <div className={`result-stage ${generatedImage ? 'has-image' : ''} ${loading ? 'is-generating' : ''}`}>
                {generatedImage ? (
                  <div className="generated-image-shell">
                    <img
                      key={generatedImage}
                      src={generatedImage}
                      alt="生成的头像"
                      className={`generated-image ${imageLoaded ? 'is-loaded' : 'is-loading'}`}
                      onLoad={() => setImageLoaded(true)}
                    />
                  </div>
                ) : !loading ? (
                  <div className="placeholder">
                    <PictureOutlined style={{ fontSize: 64, color: '#d9d9d9' }} />
                    <p>生成的头像将显示在这里</p>
                  </div>
                ) : (
                  <div className="result-skeleton" aria-hidden="true">
                    <div className="result-skeleton-frame" />
                    <div className="result-skeleton-line result-skeleton-line-short" />
                    <div className="result-skeleton-line" />
                  </div>
                )}

                {showResultOverlay && (
                  <div className="result-overlay">
                    <div className="result-overlay-beam" />
                    <div className="result-overlay-content">
                      <span className="result-overlay-badge">
                        {loading ? 'AI 生成中' : '高清图载入中'}
                      </span>
                      <Spin size="large" />
                      <strong className="result-overlay-title">{resultOverlayTitle}</strong>
                      <span className="result-overlay-description">{resultOverlayDescription}</span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </Card>
        </Col>
      </Row>
    </div>
  );
};

export default Generate;
